"tests" targets changed a bit
To ignore grep exit codes, and generaly be a bit more reliable. But
still need some work, maybe replacing make totaly...

diff --git a/examples/hello-world/Makefile b/examples/hello-world/Makefile
--- a/examples/hello-world/Makefile
+++ b/examples/hello-world/Makefile
@@ -2,6 +2,12 @@ include $(TOPDIR)/Makefile.inc
 
 EXAMPLE := hello-world
 
+TC_MACHINE := $(TESTSETDIR)/$(EXAMPLE).$(DB_PID).machine
+TC_OUT     := $(TESTSETDIR)/$(EXAMPLE).$(DB_PID).out
+
+TC_MACHINE_SCREEN := $(TESTSETDIR)/$(EXAMPLE)-screen.$(DB_PID).machine
+TC_OUT_SCREEN     := $(TESTSETDIR)/$(EXAMPLE)-screen.$(DB_PID).out
+
 
 hello-world.o: $(TOPDIR)/defs.asm hello-world.asm
 hello-world: hello-world.o
@@ -26,12 +32,44 @@ run-screen: build
 			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
 			 --set-option=binary-0:file=$(CURDIR)/hello-world \
 			 --set-option=device-3:driver=ducky.devices.terminal.StandalonePTYTerminal \
-			 -g \
-			 || touch $(TESTSET_FAILED)
+			 -g
 
 tests-pre: build
 
-tests: run run-screen
+test-run: build
+	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) $(EXAMPLE) ... "
+	$(Q) COVERAGE_FILE=$(shell if [ "$(VMCOVERAGE)" = "yes" ]; then echo "$(TESTSETDIR)/coverage/.coverage.$(EXAMPLE).$(DB_PID)"; else echo ""; fi) \
+	     $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) $(VMDEBUG) \
+			 --machine-config=$(CURDIR)/hello-world.conf \
+			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
+			 --set-option=binary-0:file=$(CURDIR)/hello-world \
+			 -g &> $(TC_MACHINE); \
+			 if [[ $$? -ne 0 ]]; then \
+			   touch $(TESTSET_FAILED); \
+				 echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   echo "$(CC_GREEN)PASS$(CC_END)"; \
+			 fi; \
+			 exit 0;
+
+test-run-screen: build
+	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) $(EXAMPLE) (screen) ... "
+	$(Q) COVERAGE_FILE=$(shell if [ "$(VMCOVERAGE)" = "yes" ]; then echo "$(TESTSETDIR)/coverage/.coverage.$(EXAMPLE)-screen.$(DB_PID)"; else echo ""; fi) \
+	     $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) $(VMDEBUG) \
+			 --machine-config=$(CURDIR)/hello-world.conf \
+			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
+			 --set-option=binary-0:file=$(CURDIR)/hello-world \
+			 --set-option=device-3:driver=ducky.devices.terminal.StandalonePTYTerminal \
+			 -g &> $(TC_MACHINE_SCREEN); \
+			 if [[ $$? -ne 0 ]]; then \
+			   touch $(TESTSET_FAILED); \
+			   echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   echo "$(CC_GREEN)PASS$(CC_END)"; \
+			 fi; \
+			 exit 0;
+
+tests: test-run test-run-screen
 
 tests-post:
 
diff --git a/tests/benchmark/simple-loop/Makefile b/tests/benchmark/simple-loop/Makefile
--- a/tests/benchmark/simple-loop/Makefile
+++ b/tests/benchmark/simple-loop/Makefile
@@ -17,10 +17,13 @@ run: simple-loop
 	     $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) $(VMDEBUG) \
 			 --machine-config=$(CURDIR)/simple-loop.conf \
 			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
-			 --set-option=binary-0:file=$(CURDIR)/simple-loop \
-			 -g 2>&1 | stdbuf -oL -eL tee $(TC_MACHINE) &> /dev/null \
-			 || touch $(TESTSET_FAILED);
-	$(Q) echo "$(CC_GREEN)`grep 'Executed instructions' $(TC_MACHINE) | awk '{print $$5, $$6, $$7}'`$(CC_END)"
+			 --set-option=binary-0:file=$(CURDIR)/simple-loop -g &> $(TC_MACHINE); \
+			 if [[ $$? -ne 0 ]]; then \
+			   touch $(TESTSET_FAILED); \
+				 echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   echo "$(CC_GREEN)`grep 'Executed instructions' $(TC_MACHINE) | awk '{print $$5, $$6, $$7}'`$(CC_END)"; \
+			 fi;
 
 tests-pre:
 
diff --git a/tests/compiler/examples/hello-world-ptr/Makefile b/tests/compiler/examples/hello-world-ptr/Makefile
--- a/tests/compiler/examples/hello-world-ptr/Makefile
+++ b/tests/compiler/examples/hello-world-ptr/Makefile
@@ -42,19 +42,24 @@ tests: build
 			  --set-device-option=device-3:stream_out=$(TC_OUT) \
 			  $(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
 			  $(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
-	 	 	  $(VMDEBUG) $(VMDEBUG_OPEN_FILES) 2>&1 | stdbuf -oL -eL tee $(TC_MACHINE) | grep -v -e '\[INFO\] ' -e '#> ' | cat &> /dev/null \
-				|| touch $(TESTSET_FAILED);
-	-$(Q) if [ -f $(TC_EXPECTED) ]; then diff -u $(TC_EXPECTED) $(TC_OUT) | cat &> $(TC_DIFF); fi
-	-$(Q) if [ ! -s $(TC_FILTERED) ] && ([ ! -f $(TC_DIFF) ] || [ ! -s $(TC_DIFF) ]); then \
-	        $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$<; \
-					echo "$(CC_GREEN)PASS$(CC_END)"; \
-				else \
-				  [ -f $(TC_FILTERED) ] && cat $(TC_FILTERED) >> $(TC_TMPFILE); \
-					[ -f $(TC_DIFF) ] && cat $(TC_DIFF) >> $(TC_TMPFILE); \
-					$(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Failed aserts" --diff=$(TC_TMPFILE); \
-					echo "$(CC_RED)FAIL$(CC_END)"; \
-					sed 's/^/  /' $(TC_TMPFILE); \
+	 	 	  $(VMDEBUG) $(VMDEBUG_OPEN_FILES) &> $(TC_MACHINE); \
+				if [[ $$? -ne 0 ]]; then \
+				  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Unexpected exit code" --diff=$(TC_MACHINE); \
 					touch $(TESTSET_FAILED); \
+					echo "$(CC_RED)FAIL$(CC_END)"; \
+				else \
+				  if [ -f $(TC_EXPECTED) ]; then diff -u $(TC_EXPECTED) $(TC_OUT) &> $(TC_DIFF) || /bin/true; fi; \
+					if [ ! -s $(TC_FILTERED) ] && ([ ! -f $(TC_DIFF) ] || [ ! -s $(TC_DIFF) ]); then \
+					  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$<; \
+						echo "$(CC_GREEN)PASS$(CC_END)"; \
+					else \
+					  [ -f $(TC_FILTERED) ] && cat $(TC_FILTERED) >> $(TC_TMPFILE); \
+					  [ -f $(TC_DIFF) ] && cat $(TC_DIFF) >> $(TC_TMPFILE); \
+					  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Failed aserts" --diff=$(TC_TMPFILE); \
+						sed 's/^/  /' $(TC_TMPFILE); \
+						touch $(TESTSET_FAILED); \
+					  echo "$(CC_RED)FAIL$(CC_END)"; \
+					fi; \
 				fi;
 	-$(Q) rm -f $(TC_TMPFILE)
 
diff --git a/tests/compiler/units/Makefile b/tests/compiler/units/Makefile
--- a/tests/compiler/units/Makefile
+++ b/tests/compiler/units/Makefile
@@ -33,21 +33,19 @@ endif
 	-$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) Compiler $(TC_NAME) ... "
 	-$(Q) $(VMCOVERAGE_FILE) \
 	      $(PYTHON) $(VMCOVERAGE_RUN) $(DCC) \
-				-i $< -o $(TC_OUT) -O0 -q \
-				$(VMDEBUG) &> $(TC_OUTPUT) \
-				|| touch $(TESTSET_FAILED); \
-				if [ "$$?" = "0" ]; then \
+				-i $< -o $(TC_OUT) -O0 -q $(VMDEBUG) &> $(TC_OUTPUT); \
+				if [[ $$? -eq 0 ]]; then \
 				  if [ -f $(TC_EXPECTED) ]; then \
 					  sed '/^  ;.*$$/d' $(TC_OUT) > $(TC_TMPFILE); \
-						diff -u $(TC_EXPECTED) $(TC_TMPFILE) | cat &> $(TC_DIFF); \
+						diff -u $(TC_EXPECTED) $(TC_TMPFILE) &> $(TC_DIFF) || /bin/true; \
 					fi; \
 					if [ ! -f $(TC_DIFF) ] || [ ! -s $(TC_DIFF) ]; then \
 					  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$<; \
 						echo "$(CC_GREEN)PASS$(CC_END)"; \
 					else \
 					  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Unexpected output" --diff=$(TC_DIFF); \
-						echo "$(CC_RED)FAIL$(CC_END)"; \
 						touch $(TESTSET_FAILED); \
+						echo "$(CC_RED)FAIL$(CC_END)"; \
 					fi; \
 				else \
 				  if [ -f $(TC_FAIL) ]; then \
@@ -58,5 +56,6 @@ endif
 						echo "$(CC_RED)FAIL$(CC_END)"; \
 						touch $(TESTSET_FAILED); \
 					fi; \
-				fi;
+				fi; \
+				exit 0;
 	-$(Q) rm -f $(TC_TMPFILE)
diff --git a/tests/forth/ans/Makefile b/tests/forth/ans/Makefile
--- a/tests/forth/ans/Makefile
+++ b/tests/forth/ans/Makefile
@@ -22,32 +22,39 @@ tests-pre:
 	$(Q) mkdir -p $(TC_DIR)
 
 tests: $(TOPDIR)/interrupts $(FORTH_KERNEL)
-	-$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) FORTH ANS testsuite ... "
-	-$(Q) $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) \
-				$(VMPROFILE) \
-				$(BINPROFILE) -g \
-				--machine-config=$(TC_CONFIG) \
-				--set-option=machine:interrupt-routines=$(INTERRUPTS) \
-				--set-option=binary-0:file=$(FORTH_KERNEL) \
-				--set-device-option=device-3:streams_in=$(CURDIR)/../enable-test-mode.f \
-				--add-device-option=device-3:streams_in=$(TOPDIR)/forth/ducky-forth.f \
-				--add-device-option=device-3:streams_in=$(CURDIR)/tester.fr \
-				$(foreach testfile,$(FORTH_ANS_TESTS),--add-device-option=device-3:streams_in=$(CURDIR)/$(testfile)) \
-				--set-device-option=device-3:stream_out=$(TC_OUTPUT) \
-				$(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
-				$(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
-				$(VMDEBUG) $(VMDEBUG_OPEN_FILES) 2>&1 | stdbuf -oL -eL tee $(TC_MACHINE) | grep -v -e '\[INFO\] ' -e '#> ' \
-				|| touch $(TESTSET_FAILED)
-	-$(Q) grep -e 'INCORRECT RESULT' -e 'WRONG NUMBER OF RESULTS' $(TC_OUTPUT) | cat > $(TC_FILTERED);
-	-$(Q) if [ ! -s $(TC_FILTERED) ]; then \
-	        $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite"; \
-					echo "$(CC_GREEN)PASS$(CC_END)"; \
-				else \
-				  $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite" --result=fail --message="Failed aserts" --diff=$(TC_FILTERED); \
-				  echo "$(CC_RED)FAIL$(CC_END)"; \
-				  sed -e 's/^/  /' $(TC_FILTERED); \
-					touch $(TESTSET_FAILED); \
-				fi
+	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) FORTH ANS testsuite ... "
+	$(Q) $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) \
+			 $(VMPROFILE) \
+			 $(BINPROFILE) -g \
+			 --machine-config=$(TC_CONFIG) \
+			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
+			 --set-option=binary-0:file=$(FORTH_KERNEL) \
+			 --set-device-option=device-3:streams_in=$(CURDIR)/../enable-test-mode.f \
+			 --add-device-option=device-3:streams_in=$(TOPDIR)/forth/ducky-forth.f \
+			 --add-device-option=device-3:streams_in=$(CURDIR)/tester.fr \
+			 $(foreach testfile,$(FORTH_ANS_TESTS),--add-device-option=device-3:streams_in=$(CURDIR)/$(testfile)) \
+			 --set-device-option=device-3:stream_out=$(TC_OUTPUT) \
+			 $(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
+			 $(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
+			 $(VMDEBUG) $(VMDEBUG_OPEN_FILES) &> $(TC_MACHINE); \
+			 if [[ $$? -ne 0 ]]; then \
+			   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite" --result=fail --message="Invalid exit code" --diff=$(TC_MACHINE); \
+			   touch $(TESTSET_FAILED); \
+				 echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   grep -v -e '\[INFO\] ' -e '#> ' $(TC_MACHINE) || /bin/true; \
+				 grep -e 'INCORRECT RESULT' -e 'WRONG NUMBER OF RESULTS' $(TC_OUTPUT) > $(TC_FILTERED) || /bin/true; \
+				 if [ ! -s $(TC_FILTERED) ]; then \
+	         $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite"; \
+					 echo "$(CC_GREEN)PASS$(CC_END)"; \
+				 else \
+				   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name="ANS test suite" --result=fail --message="Failed aserts" --diff=$(TC_FILTERED); \
+					 sed -e 's/^/  /' $(TC_FILTERED); \
+					 touch $(TESTSET_FAILED); \
+				   echo "$(CC_RED)FAIL$(CC_END)"; \
+				 fi; \
+			 fi; \
+			 exit 0;
 
 tests-post:
 
diff --git a/tests/forth/units/Makefile b/tests/forth/units/Makefile
--- a/tests/forth/units/Makefile
+++ b/tests/forth/units/Makefile
@@ -25,38 +25,45 @@ ifeq ($(VMCOVERAGE),yes)
 else
 	$(eval VMCOVERAGE_FILE := )
 endif
-	-$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) FORTH $(TC_NAME) ... "
-	-$(Q) PYTHONUNBUFFERED=yes \
-	      $(VMCOVERAGE_FILE) \
-	      $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) \
-				$(VMPROFILE) \
-				$(BINPROFILE) -g \
-				--machine-config=$(TC_CONFIG) \
-				--set-option=machine:interrupt-routines=$(INTERRUPTS) \
-				--set-option=binary-0:file=$(FORTH_KERNEL) \
-				--set-device-option=device-3:streams_in=$(CURDIR)/../enable-test-mode.f \
-				--add-device-option=device-3:streams_in=$(TOPDIR)/forth/ducky-forth.f \
-				--add-device-option=device-3:streams_in=$(CURDIR)/../ans/tester.fr \
-				--add-device-option=device-3:streams_in=$< \
-				--add-device-option=device-3:streams_in=$(CURDIR)/../run-test-word.f \
-				--set-device-option=device-3:stream_out=$(TC_OUTPUT) \
-				$(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
-				$(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
-				$(VMDEBUG) $(VMDEBUG_OPEN_FILES) 2>&1 | stdbuf -oL -eL tee $(TC_MACHINE) | grep -v -e '\[INFO\] ' -e '#> ' | cat &> /dev/null \
-				|| touch $(TESTSET_FAILED)
-	-$(Q) grep -e 'INCORRECT RESULT' -e 'WRONG NUMBER OF RESULTS' $(TC_OUTPUT) | cat > $(TC_FILTERED) || /bin/true
-	-$(Q) if [ -f $(TC_EXPECTED) ]; then diff -u $(TC_EXPECTED) $(TC_OUTPUT) | cat &> $(TC_DIFF); fi
-	-$(Q) if [ ! -s $(TC_FILTERED) ] && ([ ! -f $(TC_DIFF) ] || [ ! -s $(TC_DIFF) ]); then \
-	        $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$<; \
-					echo "$(CC_GREEN)PASS$(CC_END)"; \
-				else \
-				  [ -f $(TC_FILTERED) ] && cat $(TC_FILTERED) >> $(TC_TMPFILE); \
-					[ -f $(TC_DIFF) ] && cat $(TC_DIFF) >> $(TC_TMPFILE); \
-					$(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Failed aserts" --diff=$(TC_TMPFILE); \
-					echo "$(CC_RED)FAIL$(CC_END)"; \
-					sed 's/^/  /' $(TC_TMPFILE); \
-					touch $(TESTSET_FAILED); \
-				fi;
+	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) FORTH $(TC_NAME) ... "
+	$(Q) PYTHONUNBUFFERED=yes \
+	     $(VMCOVERAGE_FILE) \
+	     $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) \
+			 $(VMPROFILE) \
+			 $(BINPROFILE) -g \
+			 --machine-config=$(TC_CONFIG) \
+			 --set-option=machine:interrupt-routines=$(INTERRUPTS) \
+			 --set-option=binary-0:file=$(FORTH_KERNEL) \
+			 --set-device-option=device-3:streams_in=$(CURDIR)/../enable-test-mode.f \
+			 --add-device-option=device-3:streams_in=$(TOPDIR)/forth/ducky-forth.f \
+			 --add-device-option=device-3:streams_in=$(CURDIR)/../ans/tester.fr \
+			 --add-device-option=device-3:streams_in=$< \
+			 --add-device-option=device-3:streams_in=$(CURDIR)/../run-test-word.f \
+			 --set-device-option=device-3:stream_out=$(TC_OUTPUT) \
+			 $(foreach device,$(DUCKY_ENABLE_DEVICES),--enable-device=$(device)) \
+			 $(foreach device,$(DUCKY_DISABLE_DEVICES),--disable-device=$(device)) \
+			 $(VMDEBUG) $(VMDEBUG_OPEN_FILES) &> $(TC_MACHINE); \
+			 if [[ $$? -ne 0 ]]; then \
+			   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Invalid exit code" --diff=$(TC_MACHINE); \
+			   touch $(TESTSET_FAILED); \
+				 echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   grep -v -e '\[INFO\] ' -e '#> ' $(TC_MACHINE) || /bin/true; \
+				 grep -e 'INCORRECT RESULT' -e 'WRONG NUMBER OF RESULTS' $(TC_OUTPUT) > $(TC_FILTERED) || /bin/true; \
+				 if [ -f $(TC_EXPECTED) ]; then diff -u $(TC_EXPECTED) $(TC_OUTPUT) &> $(TC_DIFF) || /bin/true; fi; \
+				 if [ ! -s $(TC_FILTERED) ] && ([ ! -f $(TC_DIFF) ] || [ ! -s $(TC_DIFF) ]); then \
+				   $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$<; \
+					 echo "$(CC_GREEN)PASS$(CC_END)"; \
+				 else \
+				   [ -f $(TC_FILTERED) ] && cat $(TC_FILTERED) >> $(TC_TMPFILE); \
+					 [ -f $(TC_DIFF) ] && cat $(TC_DIFF) >> $(TC_TMPFILE); \
+					 $(XUNIT) --add --file=$(TC_RESULTS) --ts=$(TC_TESTSUITE) --name=$(TC_NAME) --classname=$< --result=fail --message="Failed aserts" --diff=$(TC_TMPFILE); \
+					 sed 's/^/  /' $(TC_TMPFILE); \
+					 touch $(TESTSET_FAILED); \
+					 echo "$(CC_RED)FAIL$(CC_END)"; \
+				 fi; \
+			 fi; \
+			 exit 0;
 	-$(Q) rm -f $(TC_TMPFILE)
 
 tests-post:
