Redirect clock machine output to file for a testrun

diff --git a/examples/clock/Makefile b/examples/clock/Makefile
--- a/examples/clock/Makefile
+++ b/examples/clock/Makefile
@@ -1,8 +1,9 @@
 include $(TOPDIR)/Makefile.inc
 
+EXAMPLE := clock
 
-TC_NAME := clock
-TC_OUT := $(TESTSETDIR)/$(TC_NAME).$(DB_PID).out
+TC_OUT := $(TESTSETDIR)/$(EXAMPLE).$(DB_PID).out
+TC_MACHINE := $(TESTSETDIR)/$(EXAMPLE).$(DB_PID).machine
 
 
 clock.o: $(TOPDIR)/defs.asm clock.asm
@@ -23,14 +24,21 @@ run: build
 tests-pre: build
 
 tests: build
-	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) clock ... "
+	$(Q) echo -n "$(CC_YELLOW)[TEST]$(CC_END) $(EXAMPLE) ... "
 	$(Q) COVERAGE_FILE=$(shell if [ "$(VMCOVERAGE)" = "yes" ]; then echo "$(TESTSETDIR)/coverage/.coverage.clock.$(DB_PID)"; else echo ""; fi) \
 	     $(PYTHON) $(VMCOVERAGE_RUN) $(DVM) $(VMDEBUG) \
 			 --machine-config=$(CURDIR)/clock.conf \
 			 --set-option=machine:interrupt-routines=$(CURDIR)/clock \
 			 --set-option=binary-0:file=$(CURDIR)/clock \
 			 --set-option=device-6:stream_out=$(TC_OUT) \
-			 -g
+			 -g &> $(TC_MACHINE); \
+			 if [[ $$? -ne 0 ]]; then \
+			   touch $(TESTSET_FAILED); \
+				 echo "$(CC_RED)FAIL$(CC_END)"; \
+			 else \
+			   echo "$(CC_GREEN)PASS$(CC_END)"; \
+			 fi; \
+			 exit 0;
 
 tests-post:
 
